### ISSUE TITLE
Incorrect typespec

### ISSUE THREAD

**Issue by StareIntoTheBeard** [Bounceapp/elixir-improvmx#1]
@lennartschoch 
https://github.com/Bounceapp/elixir-improvmx/blob/816db639253c05bcee61fe29ca127df83889887c/lib/improvmx/domains.ex#L25

Since the underlying `request` function raises, the typespec for `ImprovMX.Domains.add` should have a return type of `no_return()` instead of `{:error, term()}`
<img width="531" alt="image" src="https://user-images.githubusercontent.com/1427179/186272885-2dea638d-1af9-42e8-a720-2ddf1bff755d.png">

Alternatively, we can allow this to return `{:error, error}` and handle it in the project code.

**Comment by lennartschoch** [comment]
@StareIntoTheBeard Oh, right! I actually don't know if I like that the client is raising an error... I'll take a look, thanks for the heads-up :)

**Comment by lennartschoch** [comment]
Sorry @StareIntoTheBeard, gotta admit I kind of forgot about this. Fixed it [here](https://github.com/Bounceapp/elixir-improvmx/commit/b255c54034983f6788d557919f07ea5e862b35e3).

**Comment by StareIntoTheBeard** [comment]
Looks great!
